### PR TITLE
Correct behavior when restoring the working directory

### PR DESCRIPTION
**Pull request by expipiplus1**
I'm no vimscript expert, and I don't know exactly why things weren't working with `lcd -`
The change saves the working directory to a local variable and restores it from that. This is the same as it's done elsewhere in the code.

### CODE REVIEW

**Comment by expipiplus1** [comment]
Whoops, this was based of my branch where I merged upstream in.

**Comment by mkasa** [comment]
Thank you for a pull request. Mostly looks good.

Could you recreate a pull req rebased from the current master so that we won't see unnecessary commit logs?

Additionally, the use of try/finally might be introduced as in the other part of the code. Here is a snippet of similar code.
https://github.com/mkasa/neco-ghc-lushtags/commit/9cc65fa2b3967f021c8bdf9e8ec3b914a4e710dc

**Comment by expipiplus1** [comment]
Of course, just a minute.

**Comment by expipiplus1** [comment]
Ah I remember, the reason I didn't put the try/finally block in was I was worried about catching thrown errors rather than let them bubble up to somewhere they are intended to be captured. I'm not sure if this is an issue at all in vimscript though.

**Comment by mkasa** [comment]
Then, let's add a rethrow at the end of the finally block.

``` vim
  let l:dir = getcwd()
  try
    lcd `=expand('%:p:h')`
    let l:cmd = ['lushtags'] + a:cmd
    let l:ret = s:system(l:cmd)
  finally
    lcd `=l:dir`
    throw v:exception
  endtry
```

This does not strictly equal to rethrowing in common languages,
but at least it lets errors go out of the block. See `:h rethrow` for details.

**Comment by expipiplus1** [comment]
ok, that's all in the new pull request.

**Pull request closed without merging**
